version: "3.8"

services:
  kata-bank-api:
    build: .
    container_name: kata-bank-api
    restart: always
    environment:
      - SERVER_PORT=8801
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_INITIALIZATION_MODE=always
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/kata_bank
      - SPRING_DATASOURCE_USERNAME=springuser
      - SPRING_DATASOURCE_PASSWORD=springpass
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_GENERATE_STATISTICS=false
      - JWT_SECRET=mySecretKey123456789012345678901234567890123456789012345678901234567890
      - JWT_ACCESS_TOKEN_EXPIRATION=900000
      - JWT_REFRESH_TOKEN_EXPIRATION=604800000
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin123
      - ALLOWED_ORIGINS=https://simubank.greg-labs.com
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=when-authorized
      - MANAGEMENT_HEALTH_DEFAULTS_ENABLED=true
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.kata-bank-api.rule=Host(`simubank-api.greg-labs.com`)
      - traefik.http.routers.kata-bank-api.entrypoints=websecure
      - traefik.http.routers.kata-bank-api.tls.certresolver=le
      - traefik.http.services.kata-bank-api.loadbalancer.server.port=8801

networks:
  docker_web:
    external: true
