apiVersion: v1
kind: Secret
metadata:
  name: kata-bank-secrets
type: Opaque
data:
  database-url: amRiYzpteXNxbDovL2thdGEtYmFuay1kYi5leGFtcGxlLmNvbTozMzA2L2thdGFfYmFuaz91c2VTU0w9ZmFsc2UmYWxsb3dQdWJsaWNLZXlSZXRyaWV2YWw9dHJ1ZSZzZXJ2ZXJUaW1lem9uZT1VVEM=
  database-username: a2F0YV91c2Vy
  database-password: a2F0YV9wYXNzd29yZA==
  jwt-secret: cHJvZHVjdGlvbi1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
